# theme.toml

name = "Evolve Café"
license = "Vitor Pio CC BY 3.0"
licenselink = "https://creativecommons.org/licenses/by/3.0/"
description = "Um espaço para compartilhar experiências."
homepage = "https://evolvecafe.me"
tags = ["blog",'google-analytics', 'fast', 'modern', 'minimal', 'minimalistic', 'business', 'agency-template', 'white', 'light', 'multilingual', "bootstrap", "company", "portfolio", "projects", "responsive", "themefisher"]
features = ["blog", "company", "responsive", "seo-friendly"]
min_version = "0.64.0"

[author]
  name = "Vitor Pio"
  homepage = "https://www.youtube.com/channel/UCwsRITYlQftMPezSJ8xlPWg"

[original]
  name = "Evolve Café"
  homepage = "https://evolvecafe.me"
  repo = "https://github.com/evolvecafe/site-evolve"
