################################# Default configuration ###################
baseURL = "https://evolvecafe.me"
title = "Evolve Café | Um espaço para compartilhar experiências."
theme = "site-evolve"
themesDir = "../.."
# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disableLanguages = ["fr", "en"]
disqusShortname = "" # get your shortname form here : https://disqus.com
DefaultContentLanguage = "pt"

################################# Outputs #################################
# hugo outputs
[outputs]
home = ["HTML"]

# render unsafe html
[markup.goldmark.renderer]
unsafe = true


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
page = "/"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
page = "/"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
page = "/"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
page = "/"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
page = "/"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
page = "contact/"
attributes = ""


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


#################### default parameters ################################
[params]
logo = "images/logo.png"
logo_width = "60px"
# Meta data
description = "Somos uma comunidade unida pelo propósito da troca de experiências, desenvolvimento pessoal e profissional de forma contínua."
author = "Evolve Café"
# Contact Information
email = "contatoevolvecafe@gmail.com"
location = "Campinas/SP"
# contact form action
contact_form_action = "https://formspree.io/f/mrgooaeo" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "G-Q7M58850P3" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "-22.88879717372107"
map_longitude = "-47.07665089025387"
map_marker = "images/marker.png"

# cookies
[params.cookies]
enable = true
expire_days = 90
  
############################# social site ########################
[[params.social]]
icon = "ion-social-googleplus-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-pinterest-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-dribbble-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-twitter-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"

[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


################################ Portuguese Language ########################
[Languages.pt]
languageName = "Pt"
languageCode = "pt-br"
contentDir = "content/english"
weight = 1
# copyright
copyright = "Copyright &copy; 2020 [Evolve Café](https://evolvecafe.me/) todos os direitos reservados."


######################### Portuguese navigation #############################
# main menu
[[Languages.pt.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.pt.menu.main]]
name = "Sobre"
URL = "about"
weight = 2

[[Languages.pt.menu.main]]
name = "Projeto"
URL = "project"
weight = 3

[[Languages.pt.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.pt.menu.main]]
name = "FAQ"
URL = "faq"
weight = 5


[[Languages.pt.menu.main]]
name = "Contato"
URL = "contact"
weight = 6


# footer menu
[[Languages.pt.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.pt.menu.footer]]
name = "Sobre"
URL = "about"
weight = 2

[[Languages.pt.menu.footer]]
name = "Projeto"
URL = "project"
weight = 3

[[Languages.pt.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.pt.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.pt.menu.footer]]
name = "Contato"
URL = "contact"
weight = 6

################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 2
# copyright
copyright = "Copyright &copy; 2020 [Evolve Café](https://evolvecafe.me/) All Rights Reserved."


######################### english navigation #############################
[[Languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.main]]
name = "Project"
URL = "project"
weight = 3

[[Languages.en.menu.main]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.main]]
name = "FAQ"
URL = "faq"
weight = 5


[[Languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 6


# footer menu
[[Languages.en.menu.footer]]
name = "Home"
URL = "/"
weight = 1

[[Languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 2

[[Languages.en.menu.footer]]
name = "Project"
URL = "project"
weight = 3

[[Languages.en.menu.footer]]
name = "Blog"
URL = "blog"
weight = 4

[[Languages.en.menu.footer]]
name = "FAQ"
URL = "faq"
weight = 5

[[Languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 6